name: Deploy to Sandbox Environment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

# This permissions block grants the GITHUB_TOKEN the necessary write access for pull requests.
permissions:
  pull-requests: write
  contents: read

jobs:
  deploy:
    runs-on: <TAG> #Use your desired Self-Hosted runner tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          py -m ensurepip
          py -m pip install --upgrade pip
          py -m pip install --upgrade pip
          py -m pip install pyinstaller
          py -m pip install -r requirements.txt

      #If you wish to build an exe un comment the following lines
      #- name: Build EXE with PyInstaller
      #  run: |
      #    py -m PyInstaller --onefile --name <APPNAME> main.py
          # The .exe will be at dist\<APPNAME>.exe

      - name: Deploy to sandbox directory
        shell: powershell
        run: |
          # $pr = ${{ github.event.number }}
          # $deployPath = "C:\Sandbox\PR-$pr"
          # Remove-Item -Recurse -Force $deployPath -ErrorAction SilentlyContinue
          # New-Item -ItemType Directory -Path $deployPath
          # Copy-Item -Path "dist\<APPNAME>.exe" -Destination $deployPath

          # Optional: Copy other resources (config, assets, etc.):
          # Copy-Item -Path "config.json" -Destination $deployPath

          # Determine the accessible URL:
          # If using Tailscale IP or alias with reverse proxy:
          # $url = "https://sandbox-pr-$pr.your-company.com"
          $url = "URL Not implemented for this deployment"
          $url | Out-File sandbox_url.txt

      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const sandboxUrl = fs.readFileSync('sandbox_url.txt', 'utf8').trim();
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Sandbox deployed: ${sandboxUrl}`
            });
